version: '3.1'

services:
  springboot:
    image: bhumi1431/spring-boot-mongo:1
    ports:
      - 8080:8080 
    networks:
    - springappnetwork  

  mongo:
    image: mongo 
    volumes:
      - mongodb:/data/db 
    networks:
    - springappnetwork
    
volumes:
  mongodb: 
networks:
  springappnetwork:
